@startuml

set separator none

exception InternetBankingaSystemException

package com.bigbankplc.internetbanking.component.mainframe {
    () MainframeBankingSystemFacade
    exception MainframeBankingSystemException

    InternetBankingaSystemException <|-- MainframeBankingSystemException

    MainframeBankingSystemFacade -- MainframeBankingSystemFacadeImpl
    MainframeBankingSystemFacadeImpl ..> MainframeBankingSystemException : +throws
    MainframeBankingSystemFacadeImpl ..> GetBalanceResponse : +parses
    MainframeBankingSystemFacadeImpl ..> BankingSystemConnection : +uses
    MainframeBankingSystemFacadeImpl ..> GetBalanceRequest : +creates

    abstract AbstractRequest
    abstract AbstractResponse

    AbstractRequest <|-- GetBalanceRequest
    AbstractResponse <|-- GetBalanceResponse
    BankingSystemConnection ..> AbstractRequest : +sends
    BankingSystemConnection ..> AbstractResponse : +receives
}

@enduml
